apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healingpolicies.autopilot.io
spec:
  group: autopilot.io
  names:
    kind: HealingPolicy
    plural: healingpolicies
    singular: healingpolicy
    shortNames:
      - hp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxRetries:
                  type: integer
                cooldownSeconds:
                  type: integer
                ignoreReasons:
                  type: array
                  items:
                    type: string
